### ISSUE TITLE
pics

### ISSUE THREAD

**Issue by danyfedorov** [bugdie4k/snk#1]
![image](https://user-images.githubusercontent.com/22116479/27204970-d4160da0-5236-11e7-8e68-1ee06f7bcd63.png)
![image](https://user-images.githubusercontent.com/22116479/27205151-c9a47be4-5237-11e7-9a53-c9e9557b555b.png)

**Comment by danyfedorov** [comment]
![screenshot from 2017-10-02 18-16-07](https://user-images.githubusercontent.com/22116479/31084700-cd28a432-a79d-11e7-9d14-97cff2d55aad.png)
![screen_2017-11-09_10-39-22_selection_w318-h326](https://user-images.githubusercontent.com/22116479/32595960-67f7d654-c53a-11e7-8ded-c19821fe5397.png)

**Comment by bugdie4k** [comment]
![screen_2018-03-03_01-52-48_selection_w257-h311](https://user-images.githubusercontent.com/22116479/36927354-b57f6b18-1e85-11e8-98ce-b92aae10275a.png)

**Comment by danyfedorov** [comment]
![screen_2018-03-03_01-54-13_selection_w278-h306](https://user-images.githubusercontent.com/22116479/36927367-d2a126aa-1e85-11e8-8aff-be0b19da08bd.png)
